name: Java CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clean with Maven
      run: mvn clean
    - name: Log git info
      run: |
        echo ${{ github.event.pull_request.head.ref }}
        echo ${BRANCHNAME}
        git remote -v
        git remote add private https://github.com/msnmz/java-primer-private.git
        git remote set-url private https://msnmz:${GITKEY}@github.com/msnmz/java-primer-private.git
        git remote -v
        git checkout ${BRANCHNAME}
        git push -u private HEAD:homework-${BRANCHNAME}
      env:
        BRANCHNAME: ${{ github.event.pull_request.head.ref }}
        GITKEY: ${{secrets.PASS_FOR_GIT}}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test with Maven
      run: mvn test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
